import type { Cliente, Desconto, LancamentoFinanceiro, Movimento, Parceiro, Plano, TipoMovimento } from "./types";

export const mapPlanoToDb = (p: Plano) => ({
  id: p.id,
  nome: p.nome,
  categoria: p.categoria,
  cobranca: p.cobranca,
  duracao_valor: p.duracaoValor ?? null,
  duracao_unidade: p.duracaoUnidade ?? null,
  valor_mensal: p.valorMensal,
  valor_setup: p.valorSetup,
  canais_inclusos: p.canaisInclusos,
  usuarios_inclusos: p.usuariosInclusos,
  contatos_inclusos: p.contatosInclusos,
  canais_whats_inclusos: p.canaisWhatsInclusos,
  canais_insta_inclusos: p.canaisInstaInclusos,
  canais_messenger_inclusos: p.canaisMessengerInclusos,
  inclui_ia: p.incluiIA,
  inclui_asaas: p.incluiAsaas,
  inclui_zapi: p.incluiZapi,
  inclui_transcricao: p.incluiTranscricao,
  licenca_base: p.licencaBase,
  preco_canais_exc: p.precoCanaisExc,
  preco_usuarios_exc: p.precoUsuariosExc,
  preco_contatos_exc: p.precoContatosExc,
  preco_ia: p.precoIA,
  preco_asaas: p.precoAsaas,
  preco_zapi: p.precoZapi,
  preco_transcricao_user: p.precoTranscricaoUser,
  preco_canal_whats_exc: p.precoCanalWhatsExc,
  preco_canal_insta_exc: p.precoCanalInstaExc,
  preco_canal_messenger_exc: p.precoCanalMessengerExc,
  valor_canais_exc: p.valorCanaisExc,
  valor_usuarios_exc: p.valorUsuariosExc,
  valor_contatos_exc: p.valorContatosExc,
  valor_ia: p.valorIA,
  valor_asaas: p.valorAsaas,
  valor_zapi: p.valorZapi,
  valor_transcricao_user: p.valorTranscricaoUser,
  valor_canal_whats_exc: p.valorCanalWhatsExc,
  valor_canal_insta_exc: p.valorCanalInstaExc,
  valor_canal_messenger_exc: p.valorCanalMessengerExc,
  parceiro_ids: p.parceiroIds,
  observacao: p.observacao || "",
  dia_vencimento: p.diaVencimento ?? null,
  ciclo_dia_inicial: p.cicloDiaInicial ?? 1,
  ciclo_dia_final: p.cicloDiaFinal ?? 31,
  cobranca_proporcional: p.cobrancaProporcional ?? false,
});

export const mapDbToPlano = (r: any): Plano => {
  const canaisInclusos = Number(r.canais_inclusos ?? 1);
  const whatsInc = Number(r.canais_whats_inclusos ?? 0);
  const instaInc = Number(r.canais_insta_inclusos ?? 0);
  const msgInc = Number(r.canais_messenger_inclusos ?? 0);
  const perTypeIsZero = whatsInc === 0 && instaInc === 0 && msgInc === 0;
  return ({
    id: r.id,
    nome: r.nome,
    categoria: (r.categoria === "consultoria" ? "consultoria" : "elora") as "elora" | "consultoria",
    cobranca: (r.cobranca === "unica" ? "unica" : "recorrente") as "recorrente" | "unica",
    duracaoValor: r.duracao_valor != null ? Number(r.duracao_valor) : null,
    duracaoUnidade: (r.duracao_unidade === "dias" || r.duracao_unidade === "meses" || r.duracao_unidade === "anos") ? r.duracao_unidade : null,
    valorMensal: Number(r.valor_mensal ?? 0),
    valorSetup: Number(r.valor_setup ?? 0),
    canaisInclusos,
    usuariosInclusos: Number(r.usuarios_inclusos ?? 3),
    contatosInclusos: Number(r.contatos_inclusos ?? 500),
    canaisWhatsInclusos: perTypeIsZero ? canaisInclusos : whatsInc,
    canaisInstaInclusos: instaInc,
    canaisMessengerInclusos: msgInc,
    incluiIA: Boolean(r.inclui_ia),
    incluiAsaas: Boolean(r.inclui_asaas),
    incluiZapi: Number(r.inclui_zapi ?? 0),
    incluiTranscricao: Boolean(r.inclui_transcricao),
    licencaBase: Number(r.licenca_base ?? 149.90),
    precoCanaisExc: Number(r.preco_canais_exc ?? 29.90),
    precoUsuariosExc: Number(r.preco_usuarios_exc ?? 19.90),
    precoContatosExc: Number(r.preco_contatos_exc ?? 0.045),
    precoIA: Number(r.preco_ia ?? 50.00),
    precoAsaas: Number(r.preco_asaas ?? 49.50),
    precoZapi: Number(r.preco_zapi ?? 69.00),
    precoTranscricaoUser: Number(r.preco_transcricao_user ?? 3.99),
    precoCanalWhatsExc: Number(r.preco_canal_whats_exc ?? r.preco_canais_exc ?? 29.90),
    precoCanalInstaExc: Number(r.preco_canal_insta_exc ?? r.preco_canais_exc ?? 29.90),
    precoCanalMessengerExc: Number(r.preco_canal_messenger_exc ?? r.preco_canais_exc ?? 29.90),
    valorCanaisExc: Number(r.valor_canais_exc ?? 59.90),
    valorUsuariosExc: Number(r.valor_usuarios_exc ?? 39.90),
    valorContatosExc: Number(r.valor_contatos_exc ?? 0.10),
    valorIA: Number(r.valor_ia ?? 99.00),
    valorAsaas: Number(r.valor_asaas ?? 89.00),
    valorZapi: Number(r.valor_zapi ?? 149.00),
    valorTranscricaoUser: Number(r.valor_transcricao_user ?? 7.99),
    valorCanalWhatsExc: Number(r.valor_canal_whats_exc ?? r.valor_canais_exc ?? 59.90),
    valorCanalInstaExc: Number(r.valor_canal_insta_exc ?? r.valor_canais_exc ?? 59.90),
    valorCanalMessengerExc: Number(r.valor_canal_messenger_exc ?? r.valor_canais_exc ?? 59.90),
    parceiroIds: r.parceiro_ids ?? [],
    observacao: r.observacao || "",
    diaVencimento: r.dia_vencimento != null ? Number(r.dia_vencimento) : null,
    cicloDiaInicial: r.ciclo_dia_inicial != null ? Number(r.ciclo_dia_inicial) : 1,
    cicloDiaFinal: r.ciclo_dia_final != null ? Number(r.ciclo_dia_final) : 31,
    cobrancaProporcional: Boolean(r.cobranca_proporcional),
  });
};

export const mapParceiroToDb = (p: Parceiro) => ({
  id: p.id,
  nome: p.nome,
  email: p.email,
  celular: p.celular,
  planos_vinculados: p.planosVinculados,
  observacao: p.observacao,
});

export const mapDbToParceiro = (r: any): Parceiro => ({
  id: r.id,
  nome: r.nome,
  email: r.email || "",
  celular: r.celular || "",
  planosVinculados: r.planos_vinculados || [],
  observacao: r.observacao || "",
  criadoEm: r.criado_em ? new Date(r.criado_em).toISOString().slice(0, 10) : new Date().toISOString().slice(0, 10),
});

export const mapClienteToDb = (c: Cliente) => ({
  id: c.id,
  nome: c.nome,
  plano_id: c.planoId,
  parceiro_id: c.parceiroId,
  data_inicio: c.dataInicio,
  data_vencimento: c.dataVencimento,
  data_churn: c.dataChurn,
  ciclo_personalizado: c.cicloPersonalizado ?? false,
  ciclo_dia_inicial: c.cicloDiaInicial ?? null,
  ciclo_dia_final: c.cicloDiaFinal ?? null,
  apps: c.apps,
  mau: c.mau,
  canais: c.canais,
  canais_zapi: c.canaisZapi,
  canais_whats: c.canaisWhats || 0,
  canais_insta: c.canaisInsta || 0,
  canais_messenger: c.canaisMessenger || 0,
  usuarios_ativos: c.usuariosAtivos,
  contatos_ativos: c.contatosAtivos,
  agentes_ia: c.agentesIA,
  asaas: c.asaas,
  zapi: c.zapi,
  transcricao_ia: c.transcricaoIA,
  valor_setup_pago: c.valorSetupPago,
  valor_acompanhamento: c.valorAcompanhamento,
  extras: c.extras || {},
  observacao: c.observacao,
});

export const mapDbToCliente = (r: any): Cliente => ({
  id: r.id,
  nome: r.nome,
  planoId: r.plano_id || null,
  parceiroId: r.parceiro_id || null,
  dataInicio: r.data_inicio,
  dataVencimento: r.data_vencimento || null,
  dataChurn: r.data_churn || null,
  cicloPersonalizado: Boolean(r.ciclo_personalizado),
  cicloDiaInicial: r.ciclo_dia_inicial != null ? Number(r.ciclo_dia_inicial) : null,
  cicloDiaFinal: r.ciclo_dia_final != null ? Number(r.ciclo_dia_final) : null,
  apps: Number(r.apps ?? 0),
  mau: Number(r.mau ?? 0),
  canais: Number(r.canais ?? 1),
  canaisZapi: Number(r.canais_zapi ?? 0),
  canaisWhats: Number(r.canais_whats ?? 0),
  canaisInsta: Number(r.canais_insta ?? 0),
  canaisMessenger: Number(r.canais_messenger ?? 0),
  usuariosAtivos: Number(r.usuarios_ativos ?? 3),
  contatosAtivos: Number(r.contatos_ativos ?? 500),
  agentesIA: Boolean(r.agentes_ia),
  asaas: Boolean(r.asaas),
  zapi: Boolean(r.zapi),
  transcricaoIA: Boolean(r.transcricao_ia),
  valorSetupPago: Number(r.valor_setup_pago ?? 0),
  valorAcompanhamento: Number(r.valor_acompanhamento ?? 0),
  extras: r.extras || {},
  observacao: r.observacao || "",
});

export const mapDbToMovimento = (r: any): Movimento => ({
  id: r.id,
  clienteId: r.cliente_id,
  data: r.data,
  tipo: r.tipo as TipoMovimento,
  planoId: r.plano_id,
  apps: r.apps,
  mau: r.mau,
  canais: r.canais,
  canaisWhats: r.canais_whats,
  canaisInsta: r.canais_insta,
  canaisMessenger: r.canais_messenger,
  canaisZapi: r.canais_zapi,
  usuariosAtivos: r.usuarios_ativos,
  contatosAtivos: r.contatos_ativos,
  agentesIA: r.agentes_ia,
  asaas: r.asaas,
  zapi: r.zapi,
  transcricaoIA: r.transcricao_ia,
  extras: r.extras,
  valorServico: r.valor_servico,
  observacao: r.observacao,
});

export const mapFinanceiroToDb = (l: LancamentoFinanceiro) => ({
  id: l.id,
  descricao: l.descricao,
  tipo: l.tipo,
  categoria: l.categoria || null,
  valor: l.valor,
  vencimento: l.vencimento || null,
  competencia: l.competencia || null,
  status: l.status,
  nf_emitida: l.nfEmitida,
  nf_numero: l.nfNumero || null,
  observacao: l.observacao || null,
});

export const mapDbToFinanceiro = (r: any): LancamentoFinanceiro => ({
  id: r.id,
  descricao: r.descricao,
  tipo: (r.tipo as any) ?? "custo",
  categoria: r.categoria || undefined,
  valor: Number(r.valor ?? 0),
  vencimento: r.vencimento || null,
  competencia: r.competencia || null,
  status: (r.status as any) ?? "pendente",
  nfEmitida: Boolean(r.nf_emitida),
  nfNumero: r.nf_numero || undefined,
  observacao: r.observacao || undefined,
  criadoEm: r.created_at ?? undefined,
});