/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsuariosRouteImport } from './routes/usuarios'
import { Route as ResumoRouteImport } from './routes/resumo'
import { Route as PlanosRouteImport } from './routes/planos'
import { Route as ParceirosRouteImport } from './routes/parceiros'
import { Route as OrcamentosRouteImport } from './routes/orcamentos'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'

const UsuariosRoute = UsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumoRoute = ResumoRouteImport.update({
  id: '/resumo',
  path: '/resumo',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosRoute = PlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => rootRouteImport,
} as any)
const ParceirosRoute = ParceirosRouteImport.update({
  id: '/parceiros',
  path: '/parceiros',
  getParentRoute: () => rootRouteImport,
} as any)
const OrcamentosRoute = OrcamentosRouteImport.update({
  id: '/orcamentos',
  path: '/orcamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/auth': typeof AuthRouteWithChildren
  '/clientes': typeof ClientesRoute
  '/dashboard': typeof DashboardRoute
  '/financeiro': typeof FinanceiroRoute
  '/orcamentos': typeof OrcamentosRoute
  '/parceiros': typeof ParceirosRoute
  '/planos': typeof PlanosRoute
  '/resumo': typeof ResumoRoute
  '/usuarios': typeof UsuariosRoute
  '/auth/callback': typeof AuthCallbackRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRouteWithChildren
  '/clientes': typeof ClientesRoute
  '/dashboard': typeof DashboardRoute
  '/financeiro': typeof FinanceiroRoute
  '/orcamentos': typeof OrcamentosRoute
  '/parceiros': typeof ParceirosRoute
  '/planos': typeof PlanosRoute
  '/resumo': typeof ResumoRoute
  '/usuarios': typeof UsuariosRoute
  '/auth/callback': typeof AuthCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/auth': typeof AuthRouteWithChildren
  '/clientes': typeof ClientesRoute
  '/dashboard': typeof DashboardRoute
  '/financeiro': typeof FinanceiroRoute
  '/orcamentos': typeof OrcamentosRoute
  '/parceiros': typeof ParceirosRoute
  '/planos': typeof PlanosRoute
  '/resumo': typeof ResumoRoute
  '/usuarios': typeof UsuariosRoute
  '/auth/callback': typeof AuthCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/auth'
    | '/clientes'
    | '/dashboard'
    | '/financeiro'
    | '/orcamentos'
    | '/parceiros'
    | '/planos'
    | '/resumo'
    | '/usuarios'
    | '/auth/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/clientes'
    | '/dashboard'
    | '/financeiro'
    | '/orcamentos'
    | '/parceiros'
    | '/planos'
    | '/resumo'
    | '/usuarios'
    | '/auth/callback'
  id:
    | '__root__'
    | '/auth'
    | '/clientes'
    | '/dashboard'
    | '/financeiro'
    | '/orcamentos'
    | '/parceiros'
    | '/planos'
    | '/resumo'
    | '/usuarios'
    | '/auth/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  ClientesRoute: typeof ClientesRoute
  DashboardRoute: typeof DashboardRoute
  FinanceiroRoute: typeof FinanceiroRoute
  OrcamentosRoute: typeof OrcamentosRoute
  ParceirosRoute: typeof ParceirosRoute
  PlanosRoute: typeof PlanosRoute
  ResumoRoute: typeof ResumoRoute
  UsuariosRoute: typeof UsuariosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/usuarios': {
      id: '/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof UsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resumo': {
      id: '/resumo'
      path: '/resumo'
      fullPath: '/resumo'
      preLoaderRoute: typeof ResumoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos': {
      id: '/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof PlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parceiros': {
      id: '/parceiros'
      path: '/parceiros'
      fullPath: '/parceiros'
      preLoaderRoute: typeof ParceirosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orcamentos': {
      id: '/orcamentos'
      path: '/orcamentos'
      fullPath: '/orcamentos'
      preLoaderRoute: typeof OrcamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  ClientesRoute: ClientesRoute,
  DashboardRoute: DashboardRoute,
  FinanceiroRoute: FinanceiroRoute,
  OrcamentosRoute: OrcamentosRoute,
  ParceirosRoute: ParceirosRoute,
  PlanosRoute: PlanosRoute,
  ResumoRoute: ResumoRoute,
  UsuariosRoute: UsuariosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
