/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResumoRouteImport } from './routes/resumo'
import { Route as PlanosRouteImport } from './routes/planos'
import { Route as MovimentosRouteImport } from './routes/movimentos'
import { Route as CustosRouteImport } from './routes/custos'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as IndexRouteImport } from './routes/index'

const ResumoRoute = ResumoRouteImport.update({
  id: '/resumo',
  path: '/resumo',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosRoute = PlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => rootRouteImport,
} as any)
const MovimentosRoute = MovimentosRouteImport.update({
  id: '/movimentos',
  path: '/movimentos',
  getParentRoute: () => rootRouteImport,
} as any)
const CustosRoute = CustosRouteImport.update({
  id: '/custos',
  path: '/custos',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRoute
  '/custos': typeof CustosRoute
  '/movimentos': typeof MovimentosRoute
  '/planos': typeof PlanosRoute
  '/resumo': typeof ResumoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRoute
  '/custos': typeof CustosRoute
  '/movimentos': typeof MovimentosRoute
  '/planos': typeof PlanosRoute
  '/resumo': typeof ResumoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRoute
  '/custos': typeof CustosRoute
  '/movimentos': typeof MovimentosRoute
  '/planos': typeof PlanosRoute
  '/resumo': typeof ResumoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clientes'
    | '/custos'
    | '/movimentos'
    | '/planos'
    | '/resumo'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/clientes' | '/custos' | '/movimentos' | '/planos' | '/resumo'
  id:
    | '__root__'
    | '/'
    | '/clientes'
    | '/custos'
    | '/movimentos'
    | '/planos'
    | '/resumo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClientesRoute: typeof ClientesRoute
  CustosRoute: typeof CustosRoute
  MovimentosRoute: typeof MovimentosRoute
  PlanosRoute: typeof PlanosRoute
  ResumoRoute: typeof ResumoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/resumo': {
      id: '/resumo'
      path: '/resumo'
      fullPath: '/resumo'
      preLoaderRoute: typeof ResumoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos': {
      id: '/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof PlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movimentos': {
      id: '/movimentos'
      path: '/movimentos'
      fullPath: '/movimentos'
      preLoaderRoute: typeof MovimentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custos': {
      id: '/custos'
      path: '/custos'
      fullPath: '/custos'
      preLoaderRoute: typeof CustosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClientesRoute: ClientesRoute,
  CustosRoute: CustosRoute,
  MovimentosRoute: MovimentosRoute,
  PlanosRoute: PlanosRoute,
  ResumoRoute: ResumoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
